### PR TITLE
fixed pagination bug

### LINKED ISSUE #106: Bug with page number not resetting
We need to reset pageNumber before searching.

### PR DESCRIPTION
**Pull request by Samuelfaure**
fix #106

### CODE REVIEW

File: src/components/Results.vue [hunk 1]
```diff
@@ -3,10 +3,6 @@
     <loader v-if="resultsAreLoading"></loader>
     <server-error v-else-if="serverError"></server-error>
     <template v-else-if="isSearchNotEmpty">
-      <div class="notification" v-if="informationMessage">
```
Comment (thimy) [inline src/components/Results.vue]: Why do you remove this in this PR?

Comment (Samuelfaure) [reply src/components/Results.vue]: No good reasons to do it there actually, it was just bugging me off by throwing errors in the console
